# Data base connectivity
spring:
 data:
  mongodb:
   uri: ${MONGO_URI}
   database: ${MONGO_DB_NAME}
   auto-index-creation: true
   
# Server Url
service:
 agri-bid-server:
  url: http://localhost:8083/quickconvo/	      